docs: add docs on how to configure models deployed via azure
simonw/llm pull request #337
Opened 2023-11-08 22:39 UTC by bnookala

I noted that openai models deployed to Azure were possible to utilize via `llm`, but could not find documentation on how to configure this. Thus, here it is 🎉 

This pull request adds documentation for using OpenAI models deployed via Azure OpenAI Service in `docs/other-models.md`. The most important change is the addition of instructions on how to add the model to the `extra-openai-models.yaml` file and an example of how to run a prompt against the added model using `llm`.

Main documentation changes:

* <a href="diffhunk://#diff-1c049db75a7dd8da8a8f1de60b272386d887069a862ea23d77cdce74f662f0eaR104-R136">`docs/other-models.md`</a>: Added documentation for using OpenAI models deployed via Azure OpenAI Service, including instructions on how to add the model to the `extra-openai-models.yaml` file and an example of how to run a prompt against the added model using `llm`.

2023-11-18 19:42 UTC, Rajesh-Veeranki commented
Thanks for the documentation. I tried and it works. However, do you know if we can use the same approach for embedding models on Azure?

2023-11-24 16:29 UTC, bnookala commented
> Thanks for the documentation. I tried and it works. However, do you know if we can use the same approach for embedding models on Azure?

Thanks for verifying! I took a look at this, and I don't think this is possible without implementing a plugin to load custom embedding models. Might take an attempt at this over the weekend :)

2023-12-29 23:10 UTC, pamelafox commented on docs/other-models.md
> +LLM supports OpenAI models deployed via [Azure OpenAI Service](https://azure.microsoft.com/en-us/products/ai-services/openai-service). These can also be added using the same configuration mechanism.
```suggestion
LLM supports OpenAI models deployed via [Azure OpenAI Service](https://azure.microsoft.com/products/ai-services/openai-service). These can also be added using the same configuration mechanism.
```

Always better to use the global link and let it redirect as needed.

2023-12-29 23:11 UTC, pamelafox commented on docs/other-models.md
> +Set `api_type` to `azure` to specify that the OpenAI client library should use the Azure OpenAI Service API.
Worth noting that "azure_ad" is not supported, as far as I can tell (keyless auth with AAD).

2023-12-29 23:18 UTC, pamelafox commented on docs/other-models.md
> +Set `api_type` to `azure` to specify that the OpenAI client library should use the Azure OpenAI Service API.
```suggestion
Set `api_type` to `azure` to specify that the OpenAI client library should use the Azure OpenAI Service API. Note that the type of `azure_ad` (keyless auth) is not yet supported.
```

2023-12-30 15:05 UTC, pamelafox commented on docs/other-models.md
> +  model_name: mygpt35
```suggestion
  model_name: gpt-35-turbo
```

This seems to have model and deployment reversed.

2023-12-30 15:05 UTC, pamelafox commented on docs/other-models.md
> +  api_engine: gpt-35-turbo-16k
```suggestion
  api_engine: mygptchat
```

2023-12-30 15:06 UTC, pamelafox commented on docs/other-models.md
> +You must also add `api_engine` to specify the base model to use, eg: `gpt-35-turbo-16k`
```suggestion
You must also add `api_engine` to specify the name of the deployment.
```

2023-12-30 15:07 UTC, pamelafox commented on docs/other-models.md
> +The `model_id` is the name LLM will use for the model. The `model_name` is the deployment name of the model on Azure OpenAI Service.
```suggestion
The `model_id` is the name LLM will use for the model. The `model_name` is the name of the model on Azure OpenAI Service, like `gpt-35-turbo-16k`.
```

2023-12-30 15:07 UTC, pamelafox commented
This now works for me after incorporating my suggestions.

2023-12-30 15:08 UTC, pamelafox requested changes
See suggestions

2024-01-13 07:23 UTC, sanzgiri commented
@pamelafox - how are you specifying the azure openai key? Is it through the same env variable "OPENAI_API_KEY"? And both api_type and api_key_name are set to "azure"?

2024-01-13 17:38 UTC, pamelafox commented
I set the key using the key feature here:
https://llm.datasette.io/en/stable/setup.html#api-keys

Since I used the key name of "azure", then yes, my api_key_name was "azure", but in theory you might set it with a different name.

Here's what my configuration looks like in ~/Library/Application Support/io.datasette.llm/extra-openai-models.yaml :

- model_id: azure-gpt-35
  model_name: gpt-35-turbo
  api_base: https://cog-24ccg67vinxu2.openai.azure.com
  api_key_name: azure
  api_version: 2023-05-15
  api_type: azure
  api_engine: chat

2024-01-14 18:03 UTC, sanzgiri commented
@pamelafox - thanks! I was not setting up the key, works for me now.

2024-03-08 17:25 UTC, DaniloNC commented
I haven't been able to use Azure OpenAI with the instructions provided here.
See https://github.com/simonw/llm/issues/433 and  https://github.com/simonw/llm/issues/413

Since `openai` python package > 1.0.0, the `AzureOpenAI` class is required.

There is a pending PR here:
https://github.com/simonw/llm/pull/414

2025-05-02 07:07 UTC, closed without merging